name: DefaultDance
description: Minecraft Spigot Default Dance
author: diademiemi
version: 0.1.0
main: me.diademiemi.defaultdance.DefaultDance
api-version: 1.16
commands:
  defaultdance:
    description: Command to Default Dance.
    usage: /<command>
